const { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, BorderStyle, AlignmentType } = require("docx");

function riskColor(level) {
  switch (level) {
    case "low": return "16A34A";
    case "medium": return "F59E0B";
    case "high": return "DC2626";
    case "critical": return "991B1B";
    default: return "6B7280";
  }
}

async function generateAnalysisDocx(analysis) {
  const sections = [];

  // Title
  sections.push(new Paragraph({ heading: HeadingLevel.TITLE, children: [new TextRun({ text: "Contract Analysis Report", bold: true, color: "4F46E5" })] }));
  sections.push(new Paragraph({ children: [new TextRun({ text: `Generated by ContractShield AI | ${new Date().toLocaleDateString()}`, color: "6B7280", size: 20 })] }));
  sections.push(new Paragraph({ text: "" }));

  // Meta info
  sections.push(new Paragraph({ children: [new TextRun({ text: "File: ", bold: true }), new TextRun({ text: analysis.filename || "N/A" })] }));
  sections.push(new Paragraph({ children: [new TextRun({ text: "Document Type: ", bold: true }), new TextRun({ text: analysis.document_type || "N/A" })] }));
  sections.push(new Paragraph({ children: [new TextRun({ text: "Parties: ", bold: true }), new TextRun({ text: (analysis.parties || []).join(", ") || "N/A" })] }));
  if (analysis.language_detected) {
    sections.push(new Paragraph({ children: [new TextRun({ text: "Language: ", bold: true }), new TextRun({ text: analysis.language_detected })] }));
  }
  sections.push(new Paragraph({ text: "" }));

  // Risk Score
  sections.push(new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: `Risk Score: ${analysis.overall_risk_score}/10 — ${analysis.overall_risk_label || ""}`, color: riskColor(analysis.overall_risk_score <= 3 ? "low" : analysis.overall_risk_score <= 5 ? "medium" : "high"), bold: true })] }));
  sections.push(new Paragraph({ text: "" }));

  // Summary
  sections.push(new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: "Summary", bold: true })] }));
  sections.push(new Paragraph({ text: analysis.summary || "" }));
  sections.push(new Paragraph({ text: "" }));

  // Red Flags
  if (analysis.red_flags?.length > 0) {
    sections.push(new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: "Red Flags", bold: true, color: "DC2626" })] }));
    analysis.red_flags.forEach((f) => {
      sections.push(new Paragraph({ bullet: { level: 0 }, children: [new TextRun({ text: f, color: "DC2626" })] }));
    });
    sections.push(new Paragraph({ text: "" }));
  }

  // Financial Terms
  if (analysis.financial_terms?.length > 0) {
    sections.push(new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: "Financial Terms", bold: true })] }));
    analysis.financial_terms.forEach((ft) => {
      sections.push(new Paragraph({ bullet: { level: 0 }, children: [
        new TextRun({ text: ft.item + ": ", bold: true }),
        new TextRun({ text: `${ft.amount} (${ft.frequency})` }),
      ] }));
    });
    sections.push(new Paragraph({ text: "" }));
  }

  // Key Dates
  if (analysis.key_dates?.length > 0) {
    sections.push(new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: "Key Dates", bold: true })] }));
    analysis.key_dates.forEach((kd) => {
      sections.push(new Paragraph({ bullet: { level: 0 }, children: [
        new TextRun({ text: kd.event + ": ", bold: true }),
        new TextRun({ text: kd.date }),
      ] }));
    });
    sections.push(new Paragraph({ text: "" }));
  }

  // Clause Analysis
  sections.push(new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: "Clause-by-Clause Analysis", bold: true })] }));
  (analysis.clauses || []).forEach((c, i) => {
    sections.push(new Paragraph({ heading: HeadingLevel.HEADING_2, children: [
      new TextRun({ text: `${i + 1}. ${c.title} `, bold: true }),
      new TextRun({ text: `[${c.risk_level?.toUpperCase()}]`, color: riskColor(c.risk_level), bold: true }),
    ] }));
    sections.push(new Paragraph({ text: c.summary }));
    if (c.risk_reason) sections.push(new Paragraph({ children: [new TextRun({ text: "Risk: ", bold: true, color: "DC2626" }), new TextRun({ text: c.risk_reason })] }));
    if (c.recommendation) sections.push(new Paragraph({ children: [new TextRun({ text: "Recommendation: ", bold: true, color: "4F46E5" }), new TextRun({ text: c.recommendation })] }));
    if (c.legal_reference) sections.push(new Paragraph({ children: [new TextRun({ text: "Legal Reference: ", bold: true, italics: true }), new TextRun({ text: c.legal_reference, italics: true })] }));
    sections.push(new Paragraph({ text: "" }));
  });

  // Missing Clauses
  if (analysis.missing_clauses?.length > 0) {
    sections.push(new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: "Missing Clauses", bold: true, color: "F59E0B" })] }));
    analysis.missing_clauses.forEach((mc) => {
      sections.push(new Paragraph({ bullet: { level: 0 }, children: [
        new TextRun({ text: `${mc.clause} (${mc.importance}): `, bold: true }),
        new TextRun({ text: mc.reason }),
      ] }));
    });
    sections.push(new Paragraph({ text: "" }));
  }

  // Compliance Notes
  if (analysis.compliance_notes?.length > 0) {
    sections.push(new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: "Compliance Notes", bold: true })] }));
    analysis.compliance_notes.forEach((n) => sections.push(new Paragraph({ bullet: { level: 0 }, text: n })));
    sections.push(new Paragraph({ text: "" }));
  }

  // Action Items
  if (analysis.action_items?.length > 0) {
    sections.push(new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: "Recommended Actions", bold: true })] }));
    analysis.action_items.forEach((a) => sections.push(new Paragraph({ bullet: { level: 0 }, text: a })));
    sections.push(new Paragraph({ text: "" }));
  }

  // Negotiation Points
  if (analysis.negotiation_points?.length > 0) {
    sections.push(new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: "Negotiation Points", bold: true })] }));
    analysis.negotiation_points.forEach((n) => sections.push(new Paragraph({ bullet: { level: 0 }, text: n })));
    sections.push(new Paragraph({ text: "" }));
  }

  // Disclaimer
  sections.push(new Paragraph({ text: "" }));
  sections.push(new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "This analysis is for informational purposes only and does not constitute legal advice.", italics: true, color: "9CA3AF", size: 18 })] }));
  sections.push(new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "Generated by ContractShield AI — contractshield.ai", color: "9CA3AF", size: 18 })] }));

  const doc = new Document({
    creator: "ContractShield AI",
    title: `Contract Analysis - ${analysis.filename}`,
    sections: [{ children: sections }],
  });

  return Packer.toBuffer(doc);
}

module.exports = { generateAnalysisDocx };
